### ISSUE TITLE
Better icon

### ISSUE THREAD

**Issue by cassidyjames** [cassidyjames/dippi#8]
Need like a ruler or something on it

**Comment by micahilbery** [comment]
I know this issue is closed but would you be open to a new icon anyway? Here's a preview of what I have:
![video-display-measure-diagonal](https://user-images.githubusercontent.com/10608836/34850171-69111e38-f6ea-11e7-84ab-0a9574ec3b47.png) ![video-display-measure-vertical](https://user-images.githubusercontent.com/10608836/34850175-6dc11cb2-f6ea-11e7-8c70-1811732bf8fc.png) ![video-display-measure-horizontal](https://user-images.githubusercontent.com/10608836/34850197-84621c3c-f6ea-11e7-9729-d2498451d659.png)
![dippi](https://user-images.githubusercontent.com/10608836/34850147-5a78dd66-f6ea-11e7-8332-681edf4134c1.png) ![dippi64](https://user-images.githubusercontent.com/10608836/34850231-9c6f2ba8-f6ea-11e7-91b5-a54e0a41f448.png) ![dippi48](https://user-images.githubusercontent.com/10608836/34850399-37311ebc-f6eb-11e7-944e-4c89d8bd0f20.png)  ![dippi32](https://user-images.githubusercontent.com/10608836/34850439-6c0ce134-f6eb-11e7-85c3-5b73f55afdb2.png) ![dippi24](https://user-images.githubusercontent.com/10608836/34850477-a14465c0-f6eb-11e7-80fb-83de575c5ce6.png) ![dippi16](https://user-images.githubusercontent.com/10608836/34850500-c02249f8-f6eb-11e7-89af-6f1dedb89783.png)

**Comment by cassidyjames** [comment]
@TraumaD that's awesome! 

I really like the horizontal and vertical ones, but am a little more iffy on the others. The app icon is a little awkward to me because it's not showing the actual diagonal measurement (even if that doesn't make a ton of sense as a physical instrument), whereas the diagonal one looks like a non-existent type of ruler with pointy ends. :D I'm not sure what the solution for the diagonal would be.

But I like how crisp these are and how they're rulers; my simple red lines were just laziness until I could figure out how to draw rulers better.

**Comment by micahilbery** [comment]
I could probably fix the app icon to go across the actual diagonal of the screen pretty easy. As far as the diagonal ruler yeah I couldn't really figure out what to do. I can give it a bit of a think and keep you updated.

**Comment by cassidyjames** [comment]
Sounds good. Thank you very much!

**Comment by TraumaD** [comment]
![dippi2](https://user-images.githubusercontent.com/10608836/34850944-8b1c830c-f6ed-11e7-86e4-1cec3e31cceb.png)

Better?

**Comment by micahilbery** [comment]
![dippi2](https://user-images.githubusercontent.com/10608836/34851373-55c5aa38-f6ef-11e7-8dce-621b33937d8c.png) ![video-display-measure-diagonal2](https://user-images.githubusercontent.com/10608836/34851650-a3bdba7c-f6f0-11e7-8e64-b4b487eefa72.png)

Better?

**Comment by cassidyjames** [comment]
@TraumaD I like it!

**Comment by cassidyjames** [comment]
@TraumaD could you file a Pull Request with the new SVG assets, or provide them somehow? I love the changes. :)
